const SETTINGS={whatsapp:''};
const products=[
{id:'p1',name:'Polo Grone Personalizado',cat:'polo',price:45,desc:'Nombre, frase y talla a pedido.',img:'assets/productos/polo-grone.jpg'},
{id:'p2',name:'Banderola de Barrio',cat:'banderola',price:95,desc:'Formato personalizado para grupo, viaje o tribuna.',img:'assets/productos/banderola-barrio.jpg'},
{id:'p3',name:'Tela Íntima',cat:'tela',price:80,desc:'Diseño, medidas y acabados coordinados por pedido.',img:'assets/productos/tela-intima.jpg'},
{id:'p4',name:'Pack de Grupo',cat:'custom',price:160,desc:'Polo + tela o banderola para tu gente.',img:'assets/productos/pack-grupo.jpg'},
{id:'p5',name:'Polo Tribuna',cat:'polo',price:40,desc:'Modelo ligero para estadio y calle.',img:'assets/productos/polo-tribuna.jpg'},
{id:'p6',name:'Banderola Especial',cat:'banderola',price:120,desc:'Formato grande, frase y diseño a medida.',img:'assets/productos/banderola-especial.jpg'}];
const money=n=>`S/ ${n.toFixed(0)}`;let cart=JSON.parse(localStorage.getItem('rhg_cart_v2')||'[]');
function shareWhatsApp(text){const base=SETTINGS.whatsapp?`https://wa.me/${SETTINGS.whatsapp}`:'https://wa.me/';window.open(`${base}?text=${encodeURIComponent(text)}`,'_blank','noopener')}
const grid=document.getElementById('productGrid');function renderProducts(filter='all'){grid.innerHTML=products.filter(p=>filter==='all'||p.cat===filter).map(p=>`<article class="product-card"><div class="product-media"><img src="${p.img}" alt="${p.name}"></div><div class="product-info"><small>${p.cat.toUpperCase()}</small><h3>${p.name}</h3><p>${p.desc}</p><div class="product-buy"><strong>Desde ${money(p.price)}</strong><button onclick="addCart('${p.id}')">Reservar</button></div></div></article>`).join('')}
window.addCart=id=>{const p=products.find(x=>x.id===id),x=cart.find(i=>i.id===id);x?x.qty++:cart.push({...p,qty:1});saveCart();openCart()};window.removeCart=i=>{cart.splice(i,1);saveCart()};
function saveCart(){localStorage.setItem('rhg_cart_v2',JSON.stringify(cart));document.getElementById('cartCount').textContent=cart.reduce((a,b)=>a+b.qty,0);renderCart()};function renderCart(){document.getElementById('cartItems').innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-row"><div><b>${x.name}</b><small>${x.qty} × ${money(x.price)}</small></div><button onclick="removeCart(${i})">Quitar</button></div>`).join(''):'<p style="color:#8292aa">Tu pedido todavía está vacío.</p>';document.getElementById('cartTotal').textContent=money(cart.reduce((a,b)=>a+b.price*b.qty,0))}
const drawer=document.getElementById('drawer'),overlay=document.getElementById('overlay'),closeCartBtn=document.getElementById('closeCart');function openCart(){drawer.classList.add('open');overlay.classList.add('open');drawer.setAttribute('aria-hidden','false')}function closeCart(){drawer.classList.remove('open');overlay.classList.remove('open');drawer.setAttribute('aria-hidden','true')};document.getElementById('cartBtn').onclick=openCart;closeCartBtn.onclick=closeCart;overlay.onclick=closeCart;
const filters=document.getElementById('filters');filters.onclick=e=>{if(e.target.tagName!=='BUTTON')return;[...filters.children].forEach(b=>b.classList.remove('active'));e.target.classList.add('active');renderProducts(e.target.dataset.filter)};document.getElementById('sendOrder').onclick=()=>{if(!cart.length)return;const lines=cart.map(x=>`• ${x.name} x${x.qty}`).join('\n');shareWhatsApp(`Hola, quiero reservar este pedido en Rincón del Hincha Grone:\n${lines}\nTotal referencial: ${money(cart.reduce((a,b)=>a+b.price*b.qty,0))}\n¿Me confirman disponibilidad y precio final?`)};
document.getElementById('customForm').onsubmit=e=>{e.preventDefault();shareWhatsApp(`Hola, quiero cotizar un pedido personalizado en Rincón del Hincha Grone.\nNombre: ${document.getElementById('name').value}\nProducto: ${document.getElementById('type').value}\nCantidad: ${document.getElementById('qty').value}\nMedidas/talla: ${document.getElementById('size').value||'por definir'}\nIdea: ${document.getElementById('idea').value}`)};
const gallery=document.getElementById('gallery'),moreGallery=document.getElementById('moreGallery'),lightbox=document.getElementById('lightbox'),lightboxImg=document.getElementById('lightboxImg'),lightboxClose=document.getElementById('lightboxClose');const galleryFiles=Array.from({length:49},(_,i)=>`assets/galeria/trabajo-${String(i+1).padStart(2,'0')}.webp`);let galleryLimit=16;function renderGallery(){gallery.innerHTML=galleryFiles.slice(0,galleryLimit).map((src,i)=>`<button class="gallery-item" data-src="${src}" aria-label="Ver trabajo ${i+1}"><img loading="lazy" src="${src}" alt="Trabajo real ${i+1}"></button>`).join('');moreGallery.style.display=galleryLimit>=galleryFiles.length?'none':'flex'}renderGallery();moreGallery.onclick=()=>{galleryLimit=Math.min(galleryLimit+16,galleryFiles.length);renderGallery()};gallery.onclick=e=>{const b=e.target.closest('.gallery-item');if(!b)return;lightboxImg.src=b.dataset.src;lightbox.classList.add('open')};lightboxClose.onclick=()=>lightbox.classList.remove('open');lightbox.onclick=e=>{if(e.target===lightbox)lightbox.classList.remove('open')};
const menuBtn=document.getElementById('menuBtn'),nav=document.getElementById('nav');menuBtn.onclick=()=>nav.classList.toggle('open');nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const hv=document.querySelector('.hero-video'),videoSound=document.getElementById('videoSound');let muted=true;videoSound.onclick=()=>{muted=!muted;hv.muted=muted;videoSound.textContent=muted?'🔇 Video ambiente':'🔊 Video ambiente'};
renderProducts();saveCart();document.getElementById('year').textContent=new Date().getFullYear();